name = input("What is your name: ")
age = int(input("How old are you: "))
current_year = int(input("What is the current year?"))
year = str((current_year - age)+100)
print(name + " will be 100 years old in the year " + year)